export const Users = [
    {
        id: 1,
        firstName: 'John1',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 2,
        firstName: 'John2',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 3,
        firstName: 'John3',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 4,
        firstName: 'John4',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 5,
        firstName: 'John5',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 6,
        firstName: 'John6',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 7,
        firstName: 'John7',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    },
    {
        id: 8,
        firstName: 'John8',
        lastName: 'Doe',
        country: '/flag.jpg',
        email: 'john.doe@gmail.com',
        language: 'English',
        occupation: 'Freelance',
        objective: 'Fluent',
        subscription: 'Free Trial',
        image: '/avatar.jpg',
        phoneNumber: '+998932132366'
    }
    
]